# Generated by Django 5.2.8 on 2025-11-26 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('concept', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area_sqm', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('bathrooms', models.PositiveSmallIntegerField()),
                ('dimensions', models.CharField(max_length=120)),
                ('cover_image', models.ImageField(upload_to='catalog/covers/')),
                ('floor_plan_image', models.ImageField(blank=True, null=True, upload_to='catalog/floor_plans/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catalog Design',
                'verbose_name_plural': 'Catalog Designs',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogDesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.catalogdesign')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_catalog_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catalog Design Image',
                'verbose_name_plural': 'Catalog Design Images',
                'ordering': ['ordering', 'id'],
            },
        ),
    ]
