# Generated by Django 4.2.25 on 2025-12-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogdesign',
            name='style',
            field=models.CharField(choices=[('modern', 'Modern'), ('nordic', 'Nordic'), ('contemporary', 'Contemporary'), ('luxury', 'Luxury'), ('tropical', 'Tropical'), ('other', 'Other')], default='modern', max_length=20, verbose_name='House Style'),
        ),
    ]
