# Generated by Django 5.2.8 on 2025-11-26 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('land_size', models.PositiveIntegerField()),
                ('house_size', models.PositiveIntegerField()),
                ('material_grade', models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('luxury', 'Luxury')], max_length=20)),
                ('floors', models.PositiveSmallIntegerField()),
                ('estimate_min', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estimate_max', models.DecimalField(decimal_places=2, max_digits=14)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
