# Generated by Django 5.2.8 on 2025-11-26 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('designs', '0001_initial'),
        ('quotes', '0002_estimateinquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quote',
            name='catalog_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='catalog.catalogdesign'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='designs.housedesign'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('design', 'requested_by'), name='unique_quote_design_user'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('catalog_design', 'requested_by'), name='unique_quote_catalog_user'),
        ),
    ]
